In [1]:
import pandas as pd
import os
import numpy as np
import plotly.graph_objects as go


In [2]:
folder = 'SIDD'

compare = ['DHDN_Compare_Kernels', 'DHDN_Compare_Up', 'DHDN_Compare_Down', 
           'DHDN_Compare_Size', 'DHDN_Compare_Channel_Number']

files_compare = []
for compare_ in compare:
    name = folder + '/' + compare_ + '/'
    temp = [name + i + '/data.csv' for i in os.listdir(name)]
    files_compare.append(temp)

In [3]:
files_compare

[['SIDD/DHDN_Compare_Kernels/2023_10_13__18_26_40/data.csv',
  'SIDD/DHDN_Compare_Kernels/2023_10_14__14_11_44/data.csv'],
 ['SIDD/DHDN_Compare_Up/2023_10_12__22_31_59/data.csv',
  'SIDD/DHDN_Compare_Up/2023_10_12__13_40_23/data.csv',
  'SIDD/DHDN_Compare_Up/2023_10_13__07_22_36/data.csv',
  'SIDD/DHDN_Compare_Up/2023_10_11__21_13_59/data.csv'],
 ['SIDD/DHDN_Compare_Down/2023_10_13__06_51_19/data.csv',
  'SIDD/DHDN_Compare_Down/2023_10_11__21_12_21/data.csv',
  'SIDD/DHDN_Compare_Down/2023_10_12__13_40_44/data.csv',
  'SIDD/DHDN_Compare_Down/2023_10_12__22_17_04/data.csv'],
 ['SIDD/DHDN_Compare_Size/2023_10_09__08_38_41/data.csv',
  'SIDD/DHDN_Compare_Size/2023_10_08__23_04_55/data.csv',
  'SIDD/DHDN_Compare_Size/2023_10_08__13_31_11/data.csv',
  'SIDD/DHDN_Compare_Size/2023_10_08__14_10_25/data.csv'],
 ['SIDD/DHDN_Compare_Channel_Number/2023_10_11__08_14_43/data.csv',
  'SIDD/DHDN_Compare_Channel_Number/2023_10_10__23_14_45/data.csv',
  'SIDD/DHDN_Compare_Channel_Number/2023_10_10__14

In [8]:
metrics_loss, metrics_psnr, metrics_ssim = [], [], []
keys = []

for file_compare in files_compare:
    temp_loss, temp_psnr, temp_ssim = [], [], []
    for compare_ in file_compare:
        df = pd.read_csv(compare_)
        val_keys_loss = [i for i in df.keys() if 'Val' in i and 'Loss' in i]
        temp_loss.append(df[val_keys_loss].tail(1).to_numpy()[0])
        
        val_keys_psnr = [i for i in df.keys() if 'Val' in i and 'PSNR' in i]
        temp_psnr.append(df[val_keys_psnr].tail(1).to_numpy()[0])

        val_keys_ssim = [i for i in df.keys() if 'Val' in i and 'SSIM' in i]
        temp_ssim.append(df[val_keys_ssim].tail(1).to_numpy()[0])
    
    keys.append([val_keys_loss, val_keys_psnr, val_keys_ssim])

    metrics_loss.append(np.array(temp_loss))
    metrics_psnr.append(np.array(temp_psnr))
    metrics_ssim.append(np.array(temp_ssim))

metrics = [metrics_loss, metrics_psnr, metrics_ssim]

In [20]:
index_1 = 2 # Experiment
index_2 = 2  # Metric

compare_tag = compare[index_1]
metrics_y = metrics[index_2][index_1][:, :3]
x = keys[index_1][index_2]
y = metrics_y.mean(0)
y_m = metrics_y.min(0)
y_p = metrics_y.max(0)

In [21]:
fig = go.Figure(data=go.Scatter(x=x, y=y, name="Mean"))

fig.add_trace(go.Scatter(x=x, y=y_m, name="Minimum"))
fig.add_trace(go.Scatter(x=x, y=y_p, name="Maximum"))


fig.show()

In [42]:
metrics[0]

[array([[0.01014631, 0.01010834, 0.01003517, 0.05794189],
        [0.00975341, 0.00968216, 0.00967344, 0.05794189]]),
 array([[0.00966475, 0.00963384, 0.00964734, 0.05794189],
        [0.00968458, 0.00962807, 0.00963044, 0.05794189],
        [0.00966225, 0.0096164 , 0.00961815, 0.05794189],
        [0.01006592, 0.009966  , 0.01001579, 0.05794189]]),
 array([[0.0097083 , 0.00976907, 0.0096494 , 0.05794189],
        [0.01016738, 0.01013618, 0.01003166, 0.05794189],
        [0.00969848, 0.00978758, 0.00963235, 0.05794189],
        [0.00971616, 0.00975112, 0.00963328, 0.05794189]]),
 array([[0.01001246, 0.00966005, 0.00979327, 0.05794189],
        [0.01004054, 0.00968287, 0.00993249, 0.05794189],
        [0.01003553, 0.00966298, 0.00991382, 0.05794189],
        [0.01034169, 0.01005422, 0.0100417 , 0.05794189]]),
 array([[0.0097926 , 0.00968391, 0.00966711, 0.05794189],
        [0.009814  , 0.00968426, 0.00968688, 0.05794189],
        [0.00976227, 0.00967167, 0.00965297, 0.05794189]])]

In [69]:
metrics_final = []

for index_1 in range(3):
    temp = []
    for index_2, compare_tag in enumerate(compare):
        temp.append(metrics[index_1][index_2].mean(0))
    metrics_final.append(np.array(temp))


In [70]:
metrics_final[2]

array([[0.91365934, 0.91558296, 0.915589  , 0.35332073],
       [0.91586242, 0.91621873, 0.91617304, 0.35332073],
       [0.91535493, 0.91457405, 0.91615724, 0.35332073],
       [0.91304276, 0.91604255, 0.91557087, 0.35332073],
       [0.91573026, 0.91706391, 0.9171379 , 0.35332073]])

In [76]:
metrics_final_loss


array([[0.00994986, 0.00989525, 0.0098543 , 0.05794189],
       [0.00976938, 0.00971107, 0.00972793, 0.05794189],
       [0.00982258, 0.00986099, 0.00973667, 0.05794189],
       [0.01010756, 0.00976503, 0.00992032, 0.05794189],
       [0.00978962, 0.00967994, 0.00966898, 0.05794189]])

In [77]:
metrics_final_loss = metrics_final[0]
y_m = metrics_final_loss[:, 0]
y_t = metrics_final_loss[:, 1]
y_p = metrics_final_loss[:, 2]

In [84]:
pd_y_m = [(o - t) / t * 100 for t, o in zip(y_t, y_m)]
pd_y_t = [(o - t) / t * 100 for t, o in zip(y_t, y_t)]
pd_y_p = [(o - t) / t * 100 for t, o in zip(y_t, y_p)]

In [90]:
index = 1

metrics_final_m = metrics_final[index]
y_m = metrics_final_m[:, 0]
y_t = metrics_final_m[:, 1]
y_p = metrics_final_m[:, 2]

pd_y_m = [(o - t) / t * 100 for t, o in zip(y_t, y_m)]
pd_y_t = [(o - t) / t * 100 for t, o in zip(y_t, y_t)]
pd_y_p = [(o - t) / t * 100 for t, o in zip(y_t, y_p)]

fig = go.Figure()
fig.add_trace(go.Bar(x=compare, y=pd_y_m,
                base=pd_y_t,
                marker_color='crimson',
                name='expenses'))
fig.add_trace(go.Bar(x=compare, y=pd_y_p,
                base=pd_y_t,
                marker_color='lightslategrey',
                name='revenue'
                ))

fig.show()
